name:                polymonadic-lens
version:             0.1.0.0
github:              "ruifengx/polymonadic-lens"
license:             AllRightsReserved
author:              Ruifeng Xie
maintainer:          ruifengx@outlook.com
copyright:           "2022 All Rights Reserved"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ruifengx/polymonadic-lens#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- transformers

ghc-options:
- +RTS --io-manager=native -RTS
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
# copied from the extension set GHC2021
# copying because GHCs with GHC2021 are still not in Stack LTS
# extensions not yet supported in GHC 9.0.2 are commented out
- BangPatterns
- BinaryLiterals
- ConstrainedClassMethods
- ConstraintKinds
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DoAndIfThenElse
- EmptyCase
- EmptyDataDecls
- EmptyDataDeriving
- ExistentialQuantification
- ExplicitForAll
# - FieldSelectors
- FlexibleContexts
- FlexibleInstances
- ForeignFunctionInterface
- GADTSyntax
- GeneralisedNewtypeDeriving
- HexFloatLiterals
- ImplicitPrelude
- ImportQualifiedPost
- InstanceSigs
- KindSignatures
- MonomorphismRestriction
- MultiParamTypeClasses
- NamedFieldPuns
- NamedWildCards
- NumericUnderscores
- PatternGuards
- PolyKinds
- PostfixOperators
- RankNTypes
- RelaxedPolyRec
- ScopedTypeVariables
- StandaloneDeriving
- StandaloneKindSignatures
- StarIsType
- TraditionalRecordSyntax
- TupleSections
- TypeApplications
- TypeOperators
- TypeSynonymInstances
# custom ones below
- GADTs
- DataKinds
- TypeFamilies
- DeriveAnyClass
- DerivingStrategies
- QuantifiedConstraints
- FunctionalDependencies
- PatternSynonyms
- ViewPatterns
- LambdaCase
- BlockArguments
- DefaultSignatures

library:
  source-dirs: src

tests:
  polymonadic-lens-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - polymonadic-lens
    - hspec
    - QuickCheck
